[package]
name = "chemin"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chemin-macros = { path = "../chemin-macros" }
once_cell = "1.16.0"
route-recognizer = "0.3.1"
smallvec = "1.10.0"
