name: test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: rust:1-slim-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        run: rustup component add rustfmt && cargo fmt -- --check

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test
